import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AccountProvider } from "@/hooks/accountContext";
import "./globals.css";
import { W3StorageProvider } from "@/hooks/useW3";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MEDISTASH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <W3StorageProvider>
        <AccountProvider>
          <body className={inter.className}>{children}</body>
        </AccountProvider>
      </W3StorageProvider>
    </html>
  );
}
