import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { AccountProvider } from "@/hooks/accountContext";
import "./globals.css";
import { W3StorageProvider } from "@/hooks/useW3";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "MEDISTASH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <W3StorageProvider>
        <AccountProvider>
          <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>{children}</body>
        </AccountProvider>
      </W3StorageProvider>
    </html>
  );
}
